// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoClient024.proto

#ifndef PROTOBUF_ProtoClient024_2eproto__INCLUDED
#define PROTOBUF_ProtoClient024_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "ProtoPublic.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoClient024_2eproto();
void protobuf_AssignDesc_ProtoClient024_2eproto();
void protobuf_ShutdownFile_ProtoClient024_2eproto();

class Proto10102072;
class Proto50102072;
class Proto80101502;
class Proto80101503;
class Proto50102073;
class Proto50102074;
class Proto50401704;
class Proto10102075;
class Proto50102075;
class Proto10401705;
class Proto50401705;

// ===================================================================

class Proto10102072 : public ::google::protobuf::Message {
 public:
  Proto10102072();
  virtual ~Proto10102072();
  
  Proto10102072(const Proto10102072& from);
  
  inline Proto10102072& operator=(const Proto10102072& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto10102072& default_instance();
  
  void Swap(Proto10102072* other);
  
  // implements Message ----------------------------------------------
  
  Proto10102072* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto10102072& from);
  void MergeFrom(const Proto10102072& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto10102072)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto10102072* default_instance_;
};
// -------------------------------------------------------------------

class Proto50102072 : public ::google::protobuf::Message {
 public:
  Proto50102072();
  virtual ~Proto50102072();
  
  Proto50102072(const Proto50102072& from);
  
  inline Proto50102072& operator=(const Proto50102072& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto50102072& default_instance();
  
  void Swap(Proto50102072* other);
  
  // implements Message ----------------------------------------------
  
  Proto50102072* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto50102072& from);
  void MergeFrom(const Proto50102072& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto50102072)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 ret_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto50102072* default_instance_;
};
// -------------------------------------------------------------------

class Proto80101502 : public ::google::protobuf::Message {
 public:
  Proto80101502();
  virtual ~Proto80101502();
  
  Proto80101502(const Proto80101502& from);
  
  inline Proto80101502& operator=(const Proto80101502& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto80101502& default_instance();
  
  void Swap(Proto80101502* other);
  
  // implements Message ----------------------------------------------
  
  Proto80101502* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto80101502& from);
  void MergeFrom(const Proto80101502& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ProtoTravelTeamer left_teamers = 1;
  inline int left_teamers_size() const;
  inline void clear_left_teamers();
  static const int kLeftTeamersFieldNumber = 1;
  inline const ::ProtoTravelTeamer& left_teamers(int index) const;
  inline ::ProtoTravelTeamer* mutable_left_teamers(int index);
  inline ::ProtoTravelTeamer* add_left_teamers();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >&
      left_teamers() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >*
      mutable_left_teamers();
  
  // optional int64 left_team_id = 2;
  inline bool has_left_team_id() const;
  inline void clear_left_team_id();
  static const int kLeftTeamIdFieldNumber = 2;
  inline ::google::protobuf::int64 left_team_id() const;
  inline void set_left_team_id(::google::protobuf::int64 value);
  
  // repeated .ProtoTravelTeamer right_teamers = 3;
  inline int right_teamers_size() const;
  inline void clear_right_teamers();
  static const int kRightTeamersFieldNumber = 3;
  inline const ::ProtoTravelTeamer& right_teamers(int index) const;
  inline ::ProtoTravelTeamer* mutable_right_teamers(int index);
  inline ::ProtoTravelTeamer* add_right_teamers();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >&
      right_teamers() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >*
      mutable_right_teamers();
  
  // optional int64 right_team_id = 4;
  inline bool has_right_team_id() const;
  inline void clear_right_team_id();
  static const int kRightTeamIdFieldNumber = 4;
  inline ::google::protobuf::int64 right_team_id() const;
  inline void set_right_team_id(::google::protobuf::int64 value);
  
  // optional int64 my_team_id = 5;
  inline bool has_my_team_id() const;
  inline void clear_my_team_id();
  static const int kMyTeamIdFieldNumber = 5;
  inline ::google::protobuf::int64 my_team_id() const;
  inline void set_my_team_id(::google::protobuf::int64 value);
  
  // optional int32 fight_state = 6;
  inline bool has_fight_state() const;
  inline void clear_fight_state();
  static const int kFightStateFieldNumber = 6;
  inline ::google::protobuf::int32 fight_state() const;
  inline void set_fight_state(::google::protobuf::int32 value);
  
  // optional int32 left_tick = 7;
  inline bool has_left_tick() const;
  inline void clear_left_tick();
  static const int kLeftTickFieldNumber = 7;
  inline ::google::protobuf::int32 left_tick() const;
  inline void set_left_tick(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto80101502)
 private:
  inline void set_has_left_team_id();
  inline void clear_has_left_team_id();
  inline void set_has_right_team_id();
  inline void clear_has_right_team_id();
  inline void set_has_my_team_id();
  inline void clear_has_my_team_id();
  inline void set_has_fight_state();
  inline void clear_has_fight_state();
  inline void set_has_left_tick();
  inline void clear_has_left_tick();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer > left_teamers_;
  ::google::protobuf::int64 left_team_id_;
  ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer > right_teamers_;
  ::google::protobuf::int64 right_team_id_;
  ::google::protobuf::int64 my_team_id_;
  ::google::protobuf::int32 fight_state_;
  ::google::protobuf::int32 left_tick_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto80101502* default_instance_;
};
// -------------------------------------------------------------------

class Proto80101503 : public ::google::protobuf::Message {
 public:
  Proto80101503();
  virtual ~Proto80101503();
  
  Proto80101503(const Proto80101503& from);
  
  inline Proto80101503& operator=(const Proto80101503& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto80101503& default_instance();
  
  void Swap(Proto80101503* other);
  
  // implements Message ----------------------------------------------
  
  Proto80101503* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto80101503& from);
  void MergeFrom(const Proto80101503& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 flag = 1;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 1;
  inline ::google::protobuf::int32 flag() const;
  inline void set_flag(::google::protobuf::int32 value);
  
  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // optional int32 score = 3;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 3;
  inline ::google::protobuf::int32 score() const;
  inline void set_score(::google::protobuf::int32 value);
  
  // optional int32 reward_id = 4;
  inline bool has_reward_id() const;
  inline void clear_reward_id();
  static const int kRewardIdFieldNumber = 4;
  inline ::google::protobuf::int32 reward_id() const;
  inline void set_reward_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto80101503)
 private:
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_score();
  inline void clear_has_score();
  inline void set_has_reward_id();
  inline void clear_has_reward_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::int32 flag_;
  ::google::protobuf::int32 score_;
  ::google::protobuf::int32 reward_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto80101503* default_instance_;
};
// -------------------------------------------------------------------

class Proto50102073 : public ::google::protobuf::Message {
 public:
  Proto50102073();
  virtual ~Proto50102073();
  
  Proto50102073(const Proto50102073& from);
  
  inline Proto50102073& operator=(const Proto50102073& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto50102073& default_instance();
  
  void Swap(Proto50102073* other);
  
  // implements Message ----------------------------------------------
  
  Proto50102073* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto50102073& from);
  void MergeFrom(const Proto50102073& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 buy_times = 1;
  inline bool has_buy_times() const;
  inline void clear_buy_times();
  static const int kBuyTimesFieldNumber = 1;
  inline ::google::protobuf::int32 buy_times() const;
  inline void set_buy_times(::google::protobuf::int32 value);
  
  // optional int32 max_times = 2;
  inline bool has_max_times() const;
  inline void clear_max_times();
  static const int kMaxTimesFieldNumber = 2;
  inline ::google::protobuf::int32 max_times() const;
  inline void set_max_times(::google::protobuf::int32 value);
  
  // repeated .ProtoServerRecord server_record = 3;
  inline int server_record_size() const;
  inline void clear_server_record();
  static const int kServerRecordFieldNumber = 3;
  inline const ::ProtoServerRecord& server_record(int index) const;
  inline ::ProtoServerRecord* mutable_server_record(int index);
  inline ::ProtoServerRecord* add_server_record();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoServerRecord >&
      server_record() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoServerRecord >*
      mutable_server_record();
  
  // optional int32 score = 4;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 4;
  inline ::google::protobuf::int32 score() const;
  inline void set_score(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto50102073)
 private:
  inline void set_has_buy_times();
  inline void clear_has_buy_times();
  inline void set_has_max_times();
  inline void clear_has_max_times();
  inline void set_has_score();
  inline void clear_has_score();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 buy_times_;
  ::google::protobuf::int32 max_times_;
  ::google::protobuf::RepeatedPtrField< ::ProtoServerRecord > server_record_;
  ::google::protobuf::int32 score_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto50102073* default_instance_;
};
// -------------------------------------------------------------------

class Proto50102074 : public ::google::protobuf::Message {
 public:
  Proto50102074();
  virtual ~Proto50102074();
  
  Proto50102074(const Proto50102074& from);
  
  inline Proto50102074& operator=(const Proto50102074& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto50102074& default_instance();
  
  void Swap(Proto50102074* other);
  
  // implements Message ----------------------------------------------
  
  Proto50102074* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto50102074& from);
  void MergeFrom(const Proto50102074& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .SpecialBoxChange all_item_set = 1;
  inline int all_item_set_size() const;
  inline void clear_all_item_set();
  static const int kAllItemSetFieldNumber = 1;
  inline const ::SpecialBoxChange& all_item_set(int index) const;
  inline ::SpecialBoxChange* mutable_all_item_set(int index);
  inline ::SpecialBoxChange* add_all_item_set();
  inline const ::google::protobuf::RepeatedPtrField< ::SpecialBoxChange >&
      all_item_set() const;
  inline ::google::protobuf::RepeatedPtrField< ::SpecialBoxChange >*
      mutable_all_item_set();
  
  // @@protoc_insertion_point(class_scope:Proto50102074)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::SpecialBoxChange > all_item_set_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto50102074* default_instance_;
};
// -------------------------------------------------------------------

class Proto50401704 : public ::google::protobuf::Message {
 public:
  Proto50401704();
  virtual ~Proto50401704();
  
  Proto50401704(const Proto50401704& from);
  
  inline Proto50401704& operator=(const Proto50401704& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto50401704& default_instance();
  
  void Swap(Proto50401704* other);
  
  // implements Message ----------------------------------------------
  
  Proto50401704* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto50401704& from);
  void MergeFrom(const Proto50401704& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 fight_type = 1;
  inline bool has_fight_type() const;
  inline void clear_fight_type();
  static const int kFightTypeFieldNumber = 1;
  inline ::google::protobuf::int32 fight_type() const;
  inline void set_fight_type(::google::protobuf::int32 value);
  
  // optional int64 team_id = 2;
  inline bool has_team_id() const;
  inline void clear_team_id();
  static const int kTeamIdFieldNumber = 2;
  inline ::google::protobuf::int64 team_id() const;
  inline void set_team_id(::google::protobuf::int64 value);
  
  // optional int64 leader_id = 3;
  inline bool has_leader_id() const;
  inline void clear_leader_id();
  static const int kLeaderIdFieldNumber = 3;
  inline ::google::protobuf::int64 leader_id() const;
  inline void set_leader_id(::google::protobuf::int64 value);
  
  // optional string team_name = 4;
  inline bool has_team_name() const;
  inline void clear_team_name();
  static const int kTeamNameFieldNumber = 4;
  inline const ::std::string& team_name() const;
  inline void set_team_name(const ::std::string& value);
  inline void set_team_name(const char* value);
  inline void set_team_name(const char* value, size_t size);
  inline ::std::string* mutable_team_name();
  inline ::std::string* release_team_name();
  
  // optional int32 add_exp = 5;
  inline bool has_add_exp() const;
  inline void clear_add_exp();
  static const int kAddExpFieldNumber = 5;
  inline ::google::protobuf::int32 add_exp() const;
  inline void set_add_exp(::google::protobuf::int32 value);
  
  // repeated .ProtoTeamer teamer = 6;
  inline int teamer_size() const;
  inline void clear_teamer();
  static const int kTeamerFieldNumber = 6;
  inline const ::ProtoTeamer& teamer(int index) const;
  inline ::ProtoTeamer* mutable_teamer(int index);
  inline ::ProtoTeamer* add_teamer();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoTeamer >&
      teamer() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoTeamer >*
      mutable_teamer();
  
  // optional .ProtoPeakQualityInfo quality_info = 7;
  inline bool has_quality_info() const;
  inline void clear_quality_info();
  static const int kQualityInfoFieldNumber = 7;
  inline const ::ProtoPeakQualityInfo& quality_info() const;
  inline ::ProtoPeakQualityInfo* mutable_quality_info();
  inline ::ProtoPeakQualityInfo* release_quality_info();
  
  // optional .ProtoPeakKnockoutInfo knockout_info = 8;
  inline bool has_knockout_info() const;
  inline void clear_knockout_info();
  static const int kKnockoutInfoFieldNumber = 8;
  inline const ::ProtoPeakKnockoutInfo& knockout_info() const;
  inline ::ProtoPeakKnockoutInfo* mutable_knockout_info();
  inline ::ProtoPeakKnockoutInfo* release_knockout_info();
  
  // optional int32 left_tick = 9;
  inline bool has_left_tick() const;
  inline void clear_left_tick();
  static const int kLeftTickFieldNumber = 9;
  inline ::google::protobuf::int32 left_tick() const;
  inline void set_left_tick(::google::protobuf::int32 value);
  
  // optional int32 is_prep = 10;
  inline bool has_is_prep() const;
  inline void clear_is_prep();
  static const int kIsPrepFieldNumber = 10;
  inline ::google::protobuf::int32 is_prep() const;
  inline void set_is_prep(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto50401704)
 private:
  inline void set_has_fight_type();
  inline void clear_has_fight_type();
  inline void set_has_team_id();
  inline void clear_has_team_id();
  inline void set_has_leader_id();
  inline void clear_has_leader_id();
  inline void set_has_team_name();
  inline void clear_has_team_name();
  inline void set_has_add_exp();
  inline void clear_has_add_exp();
  inline void set_has_quality_info();
  inline void clear_has_quality_info();
  inline void set_has_knockout_info();
  inline void clear_has_knockout_info();
  inline void set_has_left_tick();
  inline void clear_has_left_tick();
  inline void set_has_is_prep();
  inline void clear_has_is_prep();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 team_id_;
  ::google::protobuf::int64 leader_id_;
  ::google::protobuf::int32 fight_type_;
  ::google::protobuf::int32 add_exp_;
  ::std::string* team_name_;
  ::google::protobuf::RepeatedPtrField< ::ProtoTeamer > teamer_;
  ::ProtoPeakQualityInfo* quality_info_;
  ::ProtoPeakKnockoutInfo* knockout_info_;
  ::google::protobuf::int32 left_tick_;
  ::google::protobuf::int32 is_prep_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto50401704* default_instance_;
};
// -------------------------------------------------------------------

class Proto10102075 : public ::google::protobuf::Message {
 public:
  Proto10102075();
  virtual ~Proto10102075();
  
  Proto10102075(const Proto10102075& from);
  
  inline Proto10102075& operator=(const Proto10102075& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto10102075& default_instance();
  
  void Swap(Proto10102075* other);
  
  // implements Message ----------------------------------------------
  
  Proto10102075* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto10102075& from);
  void MergeFrom(const Proto10102075& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 index = 1;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 1;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);
  
  // optional int32 times = 2;
  inline bool has_times() const;
  inline void clear_times();
  static const int kTimesFieldNumber = 2;
  inline ::google::protobuf::int32 times() const;
  inline void set_times(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto10102075)
 private:
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_times();
  inline void clear_has_times();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 times_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto10102075* default_instance_;
};
// -------------------------------------------------------------------

class Proto50102075 : public ::google::protobuf::Message {
 public:
  Proto50102075();
  virtual ~Proto50102075();
  
  Proto50102075(const Proto50102075& from);
  
  inline Proto50102075& operator=(const Proto50102075& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto50102075& default_instance();
  
  void Swap(Proto50102075* other);
  
  // implements Message ----------------------------------------------
  
  Proto50102075* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto50102075& from);
  void MergeFrom(const Proto50102075& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);
  
  // optional int32 index = 2;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 2;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto50102075)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();
  inline void set_has_index();
  inline void clear_has_index();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 ret_;
  ::google::protobuf::int32 index_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto50102075* default_instance_;
};
// -------------------------------------------------------------------

class Proto10401705 : public ::google::protobuf::Message {
 public:
  Proto10401705();
  virtual ~Proto10401705();
  
  Proto10401705(const Proto10401705& from);
  
  inline Proto10401705& operator=(const Proto10401705& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto10401705& default_instance();
  
  void Swap(Proto10401705* other);
  
  // implements Message ----------------------------------------------
  
  Proto10401705* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto10401705& from);
  void MergeFrom(const Proto10401705& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 page = 1;
  inline bool has_page() const;
  inline void clear_page();
  static const int kPageFieldNumber = 1;
  inline ::google::protobuf::int32 page() const;
  inline void set_page(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto10401705)
 private:
  inline void set_has_page();
  inline void clear_has_page();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 page_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto10401705* default_instance_;
};
// -------------------------------------------------------------------

class Proto50401705 : public ::google::protobuf::Message {
 public:
  Proto50401705();
  virtual ~Proto50401705();
  
  Proto50401705(const Proto50401705& from);
  
  inline Proto50401705& operator=(const Proto50401705& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Proto50401705& default_instance();
  
  void Swap(Proto50401705* other);
  
  // implements Message ----------------------------------------------
  
  Proto50401705* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Proto50401705& from);
  void MergeFrom(const Proto50401705& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ProtoQualityRank team_list = 1;
  inline int team_list_size() const;
  inline void clear_team_list();
  static const int kTeamListFieldNumber = 1;
  inline const ::ProtoQualityRank& team_list(int index) const;
  inline ::ProtoQualityRank* mutable_team_list(int index);
  inline ::ProtoQualityRank* add_team_list();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoQualityRank >&
      team_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoQualityRank >*
      mutable_team_list();
  
  // optional .ProtoQualityRank my_team = 2;
  inline bool has_my_team() const;
  inline void clear_my_team();
  static const int kMyTeamFieldNumber = 2;
  inline const ::ProtoQualityRank& my_team() const;
  inline ::ProtoQualityRank* mutable_my_team();
  inline ::ProtoQualityRank* release_my_team();
  
  // optional int32 cur_page = 3;
  inline bool has_cur_page() const;
  inline void clear_cur_page();
  static const int kCurPageFieldNumber = 3;
  inline ::google::protobuf::int32 cur_page() const;
  inline void set_cur_page(::google::protobuf::int32 value);
  
  // optional int32 total_page = 4;
  inline bool has_total_page() const;
  inline void clear_total_page();
  static const int kTotalPageFieldNumber = 4;
  inline ::google::protobuf::int32 total_page() const;
  inline void set_total_page(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Proto50401705)
 private:
  inline void set_has_my_team();
  inline void clear_has_my_team();
  inline void set_has_cur_page();
  inline void clear_has_cur_page();
  inline void set_has_total_page();
  inline void clear_has_total_page();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ProtoQualityRank > team_list_;
  ::ProtoQualityRank* my_team_;
  ::google::protobuf::int32 cur_page_;
  ::google::protobuf::int32 total_page_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoClient024_2eproto();
  friend void protobuf_AssignDesc_ProtoClient024_2eproto();
  friend void protobuf_ShutdownFile_ProtoClient024_2eproto();
  
  void InitAsDefaultInstance();
  static Proto50401705* default_instance_;
};
// ===================================================================


// ===================================================================

// Proto10102072

// optional int32 type = 1;
inline bool Proto10102072::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto10102072::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto10102072::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto10102072::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 Proto10102072::type() const {
  return type_;
}
inline void Proto10102072::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// -------------------------------------------------------------------

// Proto50102072

// optional int32 ret = 1;
inline bool Proto50102072::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto50102072::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto50102072::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto50102072::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 Proto50102072::ret() const {
  return ret_;
}
inline void Proto50102072::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// -------------------------------------------------------------------

// Proto80101502

// repeated .ProtoTravelTeamer left_teamers = 1;
inline int Proto80101502::left_teamers_size() const {
  return left_teamers_.size();
}
inline void Proto80101502::clear_left_teamers() {
  left_teamers_.Clear();
}
inline const ::ProtoTravelTeamer& Proto80101502::left_teamers(int index) const {
  return left_teamers_.Get(index);
}
inline ::ProtoTravelTeamer* Proto80101502::mutable_left_teamers(int index) {
  return left_teamers_.Mutable(index);
}
inline ::ProtoTravelTeamer* Proto80101502::add_left_teamers() {
  return left_teamers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >&
Proto80101502::left_teamers() const {
  return left_teamers_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >*
Proto80101502::mutable_left_teamers() {
  return &left_teamers_;
}

// optional int64 left_team_id = 2;
inline bool Proto80101502::has_left_team_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto80101502::set_has_left_team_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto80101502::clear_has_left_team_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto80101502::clear_left_team_id() {
  left_team_id_ = GOOGLE_LONGLONG(0);
  clear_has_left_team_id();
}
inline ::google::protobuf::int64 Proto80101502::left_team_id() const {
  return left_team_id_;
}
inline void Proto80101502::set_left_team_id(::google::protobuf::int64 value) {
  set_has_left_team_id();
  left_team_id_ = value;
}

// repeated .ProtoTravelTeamer right_teamers = 3;
inline int Proto80101502::right_teamers_size() const {
  return right_teamers_.size();
}
inline void Proto80101502::clear_right_teamers() {
  right_teamers_.Clear();
}
inline const ::ProtoTravelTeamer& Proto80101502::right_teamers(int index) const {
  return right_teamers_.Get(index);
}
inline ::ProtoTravelTeamer* Proto80101502::mutable_right_teamers(int index) {
  return right_teamers_.Mutable(index);
}
inline ::ProtoTravelTeamer* Proto80101502::add_right_teamers() {
  return right_teamers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >&
Proto80101502::right_teamers() const {
  return right_teamers_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoTravelTeamer >*
Proto80101502::mutable_right_teamers() {
  return &right_teamers_;
}

// optional int64 right_team_id = 4;
inline bool Proto80101502::has_right_team_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto80101502::set_has_right_team_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto80101502::clear_has_right_team_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto80101502::clear_right_team_id() {
  right_team_id_ = GOOGLE_LONGLONG(0);
  clear_has_right_team_id();
}
inline ::google::protobuf::int64 Proto80101502::right_team_id() const {
  return right_team_id_;
}
inline void Proto80101502::set_right_team_id(::google::protobuf::int64 value) {
  set_has_right_team_id();
  right_team_id_ = value;
}

// optional int64 my_team_id = 5;
inline bool Proto80101502::has_my_team_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Proto80101502::set_has_my_team_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Proto80101502::clear_has_my_team_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Proto80101502::clear_my_team_id() {
  my_team_id_ = GOOGLE_LONGLONG(0);
  clear_has_my_team_id();
}
inline ::google::protobuf::int64 Proto80101502::my_team_id() const {
  return my_team_id_;
}
inline void Proto80101502::set_my_team_id(::google::protobuf::int64 value) {
  set_has_my_team_id();
  my_team_id_ = value;
}

// optional int32 fight_state = 6;
inline bool Proto80101502::has_fight_state() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Proto80101502::set_has_fight_state() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Proto80101502::clear_has_fight_state() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Proto80101502::clear_fight_state() {
  fight_state_ = 0;
  clear_has_fight_state();
}
inline ::google::protobuf::int32 Proto80101502::fight_state() const {
  return fight_state_;
}
inline void Proto80101502::set_fight_state(::google::protobuf::int32 value) {
  set_has_fight_state();
  fight_state_ = value;
}

// optional int32 left_tick = 7;
inline bool Proto80101502::has_left_tick() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Proto80101502::set_has_left_tick() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Proto80101502::clear_has_left_tick() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Proto80101502::clear_left_tick() {
  left_tick_ = 0;
  clear_has_left_tick();
}
inline ::google::protobuf::int32 Proto80101502::left_tick() const {
  return left_tick_;
}
inline void Proto80101502::set_left_tick(::google::protobuf::int32 value) {
  set_has_left_tick();
  left_tick_ = value;
}

// -------------------------------------------------------------------

// Proto80101503

// optional int32 flag = 1;
inline bool Proto80101503::has_flag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto80101503::set_has_flag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto80101503::clear_has_flag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto80101503::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 Proto80101503::flag() const {
  return flag_;
}
inline void Proto80101503::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
}

// optional string name = 2;
inline bool Proto80101503::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto80101503::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto80101503::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto80101503::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Proto80101503::name() const {
  return *name_;
}
inline void Proto80101503::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Proto80101503::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Proto80101503::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Proto80101503::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Proto80101503::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 score = 3;
inline bool Proto80101503::has_score() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto80101503::set_has_score() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto80101503::clear_has_score() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto80101503::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline ::google::protobuf::int32 Proto80101503::score() const {
  return score_;
}
inline void Proto80101503::set_score(::google::protobuf::int32 value) {
  set_has_score();
  score_ = value;
}

// optional int32 reward_id = 4;
inline bool Proto80101503::has_reward_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto80101503::set_has_reward_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto80101503::clear_has_reward_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto80101503::clear_reward_id() {
  reward_id_ = 0;
  clear_has_reward_id();
}
inline ::google::protobuf::int32 Proto80101503::reward_id() const {
  return reward_id_;
}
inline void Proto80101503::set_reward_id(::google::protobuf::int32 value) {
  set_has_reward_id();
  reward_id_ = value;
}

// -------------------------------------------------------------------

// Proto50102073

// optional int32 buy_times = 1;
inline bool Proto50102073::has_buy_times() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto50102073::set_has_buy_times() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto50102073::clear_has_buy_times() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto50102073::clear_buy_times() {
  buy_times_ = 0;
  clear_has_buy_times();
}
inline ::google::protobuf::int32 Proto50102073::buy_times() const {
  return buy_times_;
}
inline void Proto50102073::set_buy_times(::google::protobuf::int32 value) {
  set_has_buy_times();
  buy_times_ = value;
}

// optional int32 max_times = 2;
inline bool Proto50102073::has_max_times() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto50102073::set_has_max_times() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto50102073::clear_has_max_times() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto50102073::clear_max_times() {
  max_times_ = 0;
  clear_has_max_times();
}
inline ::google::protobuf::int32 Proto50102073::max_times() const {
  return max_times_;
}
inline void Proto50102073::set_max_times(::google::protobuf::int32 value) {
  set_has_max_times();
  max_times_ = value;
}

// repeated .ProtoServerRecord server_record = 3;
inline int Proto50102073::server_record_size() const {
  return server_record_.size();
}
inline void Proto50102073::clear_server_record() {
  server_record_.Clear();
}
inline const ::ProtoServerRecord& Proto50102073::server_record(int index) const {
  return server_record_.Get(index);
}
inline ::ProtoServerRecord* Proto50102073::mutable_server_record(int index) {
  return server_record_.Mutable(index);
}
inline ::ProtoServerRecord* Proto50102073::add_server_record() {
  return server_record_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoServerRecord >&
Proto50102073::server_record() const {
  return server_record_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoServerRecord >*
Proto50102073::mutable_server_record() {
  return &server_record_;
}

// optional int32 score = 4;
inline bool Proto50102073::has_score() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto50102073::set_has_score() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto50102073::clear_has_score() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto50102073::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline ::google::protobuf::int32 Proto50102073::score() const {
  return score_;
}
inline void Proto50102073::set_score(::google::protobuf::int32 value) {
  set_has_score();
  score_ = value;
}

// -------------------------------------------------------------------

// Proto50102074

// repeated .SpecialBoxChange all_item_set = 1;
inline int Proto50102074::all_item_set_size() const {
  return all_item_set_.size();
}
inline void Proto50102074::clear_all_item_set() {
  all_item_set_.Clear();
}
inline const ::SpecialBoxChange& Proto50102074::all_item_set(int index) const {
  return all_item_set_.Get(index);
}
inline ::SpecialBoxChange* Proto50102074::mutable_all_item_set(int index) {
  return all_item_set_.Mutable(index);
}
inline ::SpecialBoxChange* Proto50102074::add_all_item_set() {
  return all_item_set_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SpecialBoxChange >&
Proto50102074::all_item_set() const {
  return all_item_set_;
}
inline ::google::protobuf::RepeatedPtrField< ::SpecialBoxChange >*
Proto50102074::mutable_all_item_set() {
  return &all_item_set_;
}

// -------------------------------------------------------------------

// Proto50401704

// optional int32 fight_type = 1;
inline bool Proto50401704::has_fight_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto50401704::set_has_fight_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto50401704::clear_has_fight_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto50401704::clear_fight_type() {
  fight_type_ = 0;
  clear_has_fight_type();
}
inline ::google::protobuf::int32 Proto50401704::fight_type() const {
  return fight_type_;
}
inline void Proto50401704::set_fight_type(::google::protobuf::int32 value) {
  set_has_fight_type();
  fight_type_ = value;
}

// optional int64 team_id = 2;
inline bool Proto50401704::has_team_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto50401704::set_has_team_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto50401704::clear_has_team_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto50401704::clear_team_id() {
  team_id_ = GOOGLE_LONGLONG(0);
  clear_has_team_id();
}
inline ::google::protobuf::int64 Proto50401704::team_id() const {
  return team_id_;
}
inline void Proto50401704::set_team_id(::google::protobuf::int64 value) {
  set_has_team_id();
  team_id_ = value;
}

// optional int64 leader_id = 3;
inline bool Proto50401704::has_leader_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto50401704::set_has_leader_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto50401704::clear_has_leader_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto50401704::clear_leader_id() {
  leader_id_ = GOOGLE_LONGLONG(0);
  clear_has_leader_id();
}
inline ::google::protobuf::int64 Proto50401704::leader_id() const {
  return leader_id_;
}
inline void Proto50401704::set_leader_id(::google::protobuf::int64 value) {
  set_has_leader_id();
  leader_id_ = value;
}

// optional string team_name = 4;
inline bool Proto50401704::has_team_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto50401704::set_has_team_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto50401704::clear_has_team_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto50401704::clear_team_name() {
  if (team_name_ != &::google::protobuf::internal::kEmptyString) {
    team_name_->clear();
  }
  clear_has_team_name();
}
inline const ::std::string& Proto50401704::team_name() const {
  return *team_name_;
}
inline void Proto50401704::set_team_name(const ::std::string& value) {
  set_has_team_name();
  if (team_name_ == &::google::protobuf::internal::kEmptyString) {
    team_name_ = new ::std::string;
  }
  team_name_->assign(value);
}
inline void Proto50401704::set_team_name(const char* value) {
  set_has_team_name();
  if (team_name_ == &::google::protobuf::internal::kEmptyString) {
    team_name_ = new ::std::string;
  }
  team_name_->assign(value);
}
inline void Proto50401704::set_team_name(const char* value, size_t size) {
  set_has_team_name();
  if (team_name_ == &::google::protobuf::internal::kEmptyString) {
    team_name_ = new ::std::string;
  }
  team_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Proto50401704::mutable_team_name() {
  set_has_team_name();
  if (team_name_ == &::google::protobuf::internal::kEmptyString) {
    team_name_ = new ::std::string;
  }
  return team_name_;
}
inline ::std::string* Proto50401704::release_team_name() {
  clear_has_team_name();
  if (team_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = team_name_;
    team_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 add_exp = 5;
inline bool Proto50401704::has_add_exp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Proto50401704::set_has_add_exp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Proto50401704::clear_has_add_exp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Proto50401704::clear_add_exp() {
  add_exp_ = 0;
  clear_has_add_exp();
}
inline ::google::protobuf::int32 Proto50401704::add_exp() const {
  return add_exp_;
}
inline void Proto50401704::set_add_exp(::google::protobuf::int32 value) {
  set_has_add_exp();
  add_exp_ = value;
}

// repeated .ProtoTeamer teamer = 6;
inline int Proto50401704::teamer_size() const {
  return teamer_.size();
}
inline void Proto50401704::clear_teamer() {
  teamer_.Clear();
}
inline const ::ProtoTeamer& Proto50401704::teamer(int index) const {
  return teamer_.Get(index);
}
inline ::ProtoTeamer* Proto50401704::mutable_teamer(int index) {
  return teamer_.Mutable(index);
}
inline ::ProtoTeamer* Proto50401704::add_teamer() {
  return teamer_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoTeamer >&
Proto50401704::teamer() const {
  return teamer_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoTeamer >*
Proto50401704::mutable_teamer() {
  return &teamer_;
}

// optional .ProtoPeakQualityInfo quality_info = 7;
inline bool Proto50401704::has_quality_info() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Proto50401704::set_has_quality_info() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Proto50401704::clear_has_quality_info() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Proto50401704::clear_quality_info() {
  if (quality_info_ != NULL) quality_info_->::ProtoPeakQualityInfo::Clear();
  clear_has_quality_info();
}
inline const ::ProtoPeakQualityInfo& Proto50401704::quality_info() const {
  return quality_info_ != NULL ? *quality_info_ : *default_instance_->quality_info_;
}
inline ::ProtoPeakQualityInfo* Proto50401704::mutable_quality_info() {
  set_has_quality_info();
  if (quality_info_ == NULL) quality_info_ = new ::ProtoPeakQualityInfo;
  return quality_info_;
}
inline ::ProtoPeakQualityInfo* Proto50401704::release_quality_info() {
  clear_has_quality_info();
  ::ProtoPeakQualityInfo* temp = quality_info_;
  quality_info_ = NULL;
  return temp;
}

// optional .ProtoPeakKnockoutInfo knockout_info = 8;
inline bool Proto50401704::has_knockout_info() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Proto50401704::set_has_knockout_info() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Proto50401704::clear_has_knockout_info() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Proto50401704::clear_knockout_info() {
  if (knockout_info_ != NULL) knockout_info_->::ProtoPeakKnockoutInfo::Clear();
  clear_has_knockout_info();
}
inline const ::ProtoPeakKnockoutInfo& Proto50401704::knockout_info() const {
  return knockout_info_ != NULL ? *knockout_info_ : *default_instance_->knockout_info_;
}
inline ::ProtoPeakKnockoutInfo* Proto50401704::mutable_knockout_info() {
  set_has_knockout_info();
  if (knockout_info_ == NULL) knockout_info_ = new ::ProtoPeakKnockoutInfo;
  return knockout_info_;
}
inline ::ProtoPeakKnockoutInfo* Proto50401704::release_knockout_info() {
  clear_has_knockout_info();
  ::ProtoPeakKnockoutInfo* temp = knockout_info_;
  knockout_info_ = NULL;
  return temp;
}

// optional int32 left_tick = 9;
inline bool Proto50401704::has_left_tick() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Proto50401704::set_has_left_tick() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Proto50401704::clear_has_left_tick() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Proto50401704::clear_left_tick() {
  left_tick_ = 0;
  clear_has_left_tick();
}
inline ::google::protobuf::int32 Proto50401704::left_tick() const {
  return left_tick_;
}
inline void Proto50401704::set_left_tick(::google::protobuf::int32 value) {
  set_has_left_tick();
  left_tick_ = value;
}

// optional int32 is_prep = 10;
inline bool Proto50401704::has_is_prep() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Proto50401704::set_has_is_prep() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Proto50401704::clear_has_is_prep() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Proto50401704::clear_is_prep() {
  is_prep_ = 0;
  clear_has_is_prep();
}
inline ::google::protobuf::int32 Proto50401704::is_prep() const {
  return is_prep_;
}
inline void Proto50401704::set_is_prep(::google::protobuf::int32 value) {
  set_has_is_prep();
  is_prep_ = value;
}

// -------------------------------------------------------------------

// Proto10102075

// optional int32 index = 1;
inline bool Proto10102075::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto10102075::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto10102075::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto10102075::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 Proto10102075::index() const {
  return index_;
}
inline void Proto10102075::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
}

// optional int32 times = 2;
inline bool Proto10102075::has_times() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto10102075::set_has_times() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto10102075::clear_has_times() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto10102075::clear_times() {
  times_ = 0;
  clear_has_times();
}
inline ::google::protobuf::int32 Proto10102075::times() const {
  return times_;
}
inline void Proto10102075::set_times(::google::protobuf::int32 value) {
  set_has_times();
  times_ = value;
}

// -------------------------------------------------------------------

// Proto50102075

// optional int32 ret = 1;
inline bool Proto50102075::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto50102075::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto50102075::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto50102075::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 Proto50102075::ret() const {
  return ret_;
}
inline void Proto50102075::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// optional int32 index = 2;
inline bool Proto50102075::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto50102075::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto50102075::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto50102075::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 Proto50102075::index() const {
  return index_;
}
inline void Proto50102075::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
}

// -------------------------------------------------------------------

// Proto10401705

// optional int32 page = 1;
inline bool Proto10401705::has_page() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Proto10401705::set_has_page() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Proto10401705::clear_has_page() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Proto10401705::clear_page() {
  page_ = 0;
  clear_has_page();
}
inline ::google::protobuf::int32 Proto10401705::page() const {
  return page_;
}
inline void Proto10401705::set_page(::google::protobuf::int32 value) {
  set_has_page();
  page_ = value;
}

// -------------------------------------------------------------------

// Proto50401705

// repeated .ProtoQualityRank team_list = 1;
inline int Proto50401705::team_list_size() const {
  return team_list_.size();
}
inline void Proto50401705::clear_team_list() {
  team_list_.Clear();
}
inline const ::ProtoQualityRank& Proto50401705::team_list(int index) const {
  return team_list_.Get(index);
}
inline ::ProtoQualityRank* Proto50401705::mutable_team_list(int index) {
  return team_list_.Mutable(index);
}
inline ::ProtoQualityRank* Proto50401705::add_team_list() {
  return team_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoQualityRank >&
Proto50401705::team_list() const {
  return team_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoQualityRank >*
Proto50401705::mutable_team_list() {
  return &team_list_;
}

// optional .ProtoQualityRank my_team = 2;
inline bool Proto50401705::has_my_team() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Proto50401705::set_has_my_team() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Proto50401705::clear_has_my_team() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Proto50401705::clear_my_team() {
  if (my_team_ != NULL) my_team_->::ProtoQualityRank::Clear();
  clear_has_my_team();
}
inline const ::ProtoQualityRank& Proto50401705::my_team() const {
  return my_team_ != NULL ? *my_team_ : *default_instance_->my_team_;
}
inline ::ProtoQualityRank* Proto50401705::mutable_my_team() {
  set_has_my_team();
  if (my_team_ == NULL) my_team_ = new ::ProtoQualityRank;
  return my_team_;
}
inline ::ProtoQualityRank* Proto50401705::release_my_team() {
  clear_has_my_team();
  ::ProtoQualityRank* temp = my_team_;
  my_team_ = NULL;
  return temp;
}

// optional int32 cur_page = 3;
inline bool Proto50401705::has_cur_page() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Proto50401705::set_has_cur_page() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Proto50401705::clear_has_cur_page() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Proto50401705::clear_cur_page() {
  cur_page_ = 0;
  clear_has_cur_page();
}
inline ::google::protobuf::int32 Proto50401705::cur_page() const {
  return cur_page_;
}
inline void Proto50401705::set_cur_page(::google::protobuf::int32 value) {
  set_has_cur_page();
  cur_page_ = value;
}

// optional int32 total_page = 4;
inline bool Proto50401705::has_total_page() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Proto50401705::set_has_total_page() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Proto50401705::clear_has_total_page() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Proto50401705::clear_total_page() {
  total_page_ = 0;
  clear_has_total_page();
}
inline ::google::protobuf::int32 Proto50401705::total_page() const {
  return total_page_;
}
inline void Proto50401705::set_total_page(::google::protobuf::int32 value) {
  set_has_total_page();
  total_page_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoClient024_2eproto__INCLUDED
